name: CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  quick-checks:
    name: Quick Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn tsc --noEmit

      - name: Check formatting
        run: yarn prettier --check "src/**/*.ts"

      - name: Lint
        run: yarn lint


  build:
    name: Build
    runs-on: ubuntu-latest
    needs: quick-checks
    env: 
      VITE_API_URL: ${{ vars.VITE_API_URL }}
      VITE_WS_URL: ${{ vars.VITE_WS_URL }}
      VITE_IS_APP_ENABLED_FLAG: ${{ vars.VITE_IS_APP_ENABLED_FLAG }}
      VITE_IS_GAME_ENABLED_FLAG: ${{ vars.VITE_IS_GAME_ENABLED_FLAG }}
      VITE_IS_AUTH_ENABLED_FLAG: ${{ vars.VITE_IS_AUTH_ENABLED_FLAG }}
      VITE_IS_DEV_TOOLS_ENABLED_FLAG: ${{ vars.VITE_IS_DEV_TOOLS_ENABLED_FLAG }}
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
